### ISSUE TITLE
Skip unpacking if possible

### ISSUE THREAD

**Issue by joachim-durchholz-six** [maven-download-plugin/maven-download-plugin#151]
We download and unpack four JREs and two Tomcats, so they can be bundled with our installer - that's several hundred megabyes, slowing down our builds.
Having maven-download-plugin cache the download already helps, caching the unpacked data would help even more.

Possible approaches for unpacking:

1) Unpack into ${project.build.directory}.
2) Unpack into the download cache. In ${project.build.directory}, create a symlink (these do exist for Windows, Windows Explorer just doesn't have direct support for them).

Possible approaches for making sure that the unpacked files are not modified:

A) Extremely fast: Make all unpacked files read-only. This is somewhat problematic, since even if the files should never be modified in ${project.build.directory}, some or all of them may end up in places where they _should_ be modifiable. Maybe keep the attribute information in an additional file, and provide a library (and/or plugin goal) that reapplies the original attributes to whatever files are found in a directory.
B) Very fast: Compare times and timestamps.
C) Still faster than unpacking, because reading is faster than writing on SSDs and even on harddisks: Compare file checksums, which are computed during the unpacking process.

**Comment by kriegaex** [comment]
To me this feels like out of scope for a **download** plugin where unpacking is just an additional convenience option with basic functionality. I do not use it, because I have to unpack selectively, maybe just some directories inside the archive , and my target might be yet another archive. I recommend [TrueZIP Maven Plugin](https://www.mojohaus.org/truezip/truezip-maven-plugin/) for that kind of advanced stuff - see also [how I use both plugins in combination](https://github.com/kriegaex/org.aspectj/blob/lib-auto-provisioning/lib/pom.xml) in my project. But not even that more sophisticated TrueZIP plugin supports what you are dreaming about here.

Ugly as it might be, I suggest you use either an Antrun task in order to generate checksums (ugly) or maybe use [checksum Maven Plugin](https://checksum-maven-plugin.nicoulaj.net/) (I never tried, just googled it) in order to generate checksums over all unpacked files, committing the checksum files along with your download dependencies and updating them when you update your dependencies. In a subsequent step, you could generate the checksums for the existing unpacked files (if any) and simply compare the checksum file content with the content of the committed version. I just do not think that it is worth the effort, because having to calculate thousands of checksums before deciding to unzip or not, maybe is not so much faster either.

Your idea to make files read-only does not strike me as particularly helpful. Plus, it is hard to do right in a platform-independent way.

My suggestion is to create a zero-sized marker file after successful unpacking. Then wrap your download and unpack action into a profile which is auto-activated by the absence(!) of this marker file. This is blazing fast and does not check each single file. Additionally, you might want to use Maven Enforcer for checking if a handful of unpacked files exist in the expected places. In the POM I linked to earlier, you can also find that kind of thing.

**Comment by joachim-durchholz-six** [comment]
@kriegaex

I agree that unpacking is a convenience mechanism. If the download-plugin project cannot deal with all the special cases, it may indeed be a better idea to leave it to a plugin that handles all the case.
Actually download-plugin does exactly that, it delegates the unpacking to Plexus. It's just that Plexus doesn't cover this use case.

TrueZIP likely does not deal with symlink-permission issues either, it has no options how to deal with the situation.

Checksumming will tell you that something is wrong, but not why or what to do, so it's not an improvement over the current situation with a failure and a somewhat unhelpful error message.

Marker files are silent data corruption, which is completely inacceptable in a Maven build.
Also, neither Plexus nor TrueZIP offer options to do that, so it's not a viable path.

**Comment by kriegaex** [comment]
Follow the link to my POM above and you see how I manually create the marker file using. For your convenience, here is a [deep link](https://github.com/kriegaex/org.aspectj/blob/3134e569917ce3f8c8054fd1b4c05e9bd981a365/lib/pom.xml#L619-L638).

Of course, a marker file is a heuristic approach and a workaround, but it works, unless someone manually modifies a file. in the unpacked directory. In order to cover that, you really would have to keep track of checksums for each single file. But that is not a viable option IMO, too expensive.

**Comment by joachim-durchholz-six** [comment]
I was thinking that a marker file is created instead of a symlink, but you seem to mean something different.
Now that I have looked, it seems to be something different, but I don't know under what conditions it is created and for what purpose, so I can't comment further.

Manual modifications are yet another can of worms; download-plugin does not safeguard against that for the unpacked data. I did a quick investigation if that would be a useful addition, but found it's too slow for my use case so I'll leave that to people who actually could use that, because they's have much better insights into trade-offs and the degree of control needed.
IOW that's out of scope for me, and I'm not sure if it's in scope for this Issue report.

**Comment by kriegaex** [comment]
> a marker file (...) seems to be something different, but I don't know under what conditions it is created and for what purpose, so I can't comment further.

I thought my POM in combination with my words would explain it. Actually, it is very simple: If the download + unpack action succeeds, the marker file will be created in order to confirm that the dependency was unpacked. Because then the marker file exists when starting the next build and the download + unpack action is inside a Maven profile which only gets activated by the absence(!) of the marker file, it would skip any further download + unpack actions, which is exactly what you need according to your description. Simple, elegant, effective, blazingly fast.

> Manual modifications are yet another can of worms; download-plugin does not safeguard against that for the unpacked data.

Why would it? If you want to mess up your own build, you always find a way shoot into your own foot. I think the build really does not need to safe-guard against every single type of human stupidity imaginable.

> IOW that's out of scope for me, and I'm not sure if it's in scope for this Issue report.

What I suggested, specifically addresses your need and would help you solve your problem. It is not something I dreamed up in theory but something I use in my own project. Sorry to impose my solution onto you, I merely meant to help. If you refuse my help, feel free to live with your current situation which is certainly worse than what I suggested. Just because my solution is not perfect, it does not mean it is not a substantial improvement and not worth implementing. This is one of the fallacies of software development: Improvements do not happen because everyone is waiting for the magical perfect solution. I however believe in the boy scout rule: Just leave the camp ground behind a little cleaner than you found it and inevitably the world will be a better place than it used to be. Do that iteratively, and you will see substantial improvements. If tomorrow you can run your build a little more fearlessly than today, wouldn't that be nice to have?

**Comment by longtimeago** [comment]
@joachim-durchholz-six @kriegaex thanks for sharing the issue and possible solutions!

> I thought my POM in combination with my words would explain it. Actually, it is very simple:

@kriegaex our idea is quite elegant indeed :+1: 

And you are right, implementing complex conditional unpacking **in the plugin** is too much for the plugin :)
We are not going to do that, sorry @joachim-durchholz-six
