### ISSUE TITLE
TLSv1.3-only HTTPS servers not supported

### ISSUE THREAD

**Issue by rbi** [maven-download-plugin/maven-download-plugin#182]
When trying to download from an HTTPS Server that supports only TLSv1.3 the plugin fails. TLSv1.3 is not in the list of supported protocols of the plugin:

https://github.com/maven-download-plugin/maven-download-plugin/blob/master/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java#L107

**Comment by longtimeago** [comment]
@rbi Right, that's because TLSv1.3 is officially supported starting from Java 11 and backported to some Java 8
- Amazon Coretto (from `8u272`)
- Oracle JDK (from `8u261`)
- Azul JDK (from `8u262`)

The plugin minimal version is Java 8. So we can't just add TLSv1.3 to the list, as this will break users on older Java 8 version.
But we can probe supported protocols and add TLSv1.3 to the list only if it is supported by running java
 
Definitely worth the effort, thanks for reporting!

**Comment by rbi** [comment]
Thanks for looking into it so quickly.

An alternative to explicitly defining supported protocols would be to just use the protocol "TLS" or maybe "SSL". The JVM than can decide which versions are supported. It should be possible to explicitly override that decision by setting `jdk.tls.client.protocols` and/or `https.protocols`[1] (not thoroughly tested). This way it should be possible to support TLSv1.4 without modifying code once it appears.

Your solution would work for me too however.

\[1\]: https://docs.oracle.com/en/java/javase/11/security/java-secure-socket-extension-jsse-reference-guide.html#GUID-A41282C3-19A3-400A-A40F-86F4DA22ABA9

**Comment by longtimeago** [comment]
@rbi thanks for the hint! Let me keep it like this for now. Just have no enough time to check other options :(
