### ISSUE TITLE
[Question] Is it possible to invoke the maven plugin directly from java code ?

### ISSUE THREAD

**Issue by p4535992** [maven-download-plugin/maven-download-plugin#232]
Hi i have always used the maven plugin at the maven level or shell commands. Now I have a need to use the project following a true or false in a java code.

Is this possible ? If yes can you point me to an example to use as a reference ?

To understand I need to download a maven artifact from a main method of a java class.

**Comment by ajarmoniuk** [comment]
Yes, it is possible to do that. Not super easy since it depends on Maven libraries and a dependency injection framework based on Google Guice to retrieve some components.

A few different approaches can be found e.g. here: https://stackoverflow.com/questions/2146580/how-to-programmatically-call-a-maven-task

But if you're only after downloading files, you could probably just use the underlying Apache HttpClient or another library like Eclipse Jetty.

**Comment by p4535992** [comment]
Ty very much for the advise i'll try that
